import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Activity, Ban, BarChart3, Clock3, Coins, Gauge, History, Loader2, RefreshCw, Save, Search, ShieldCheck, Users } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";

type UserRow={id:string;username:string;avatar:string;platform:string;coins:number;streak:number;status:string;joined_date:string;last_active:string|null;reputation:number;email:string|null};
type Controls={app:Record<string,any>;ads:Record<string,any>;crush:Record<string,any>};
const APP_FLAGS:[string,string][]=[["dating_enabled","Dating"],["live_stream_enabled","Live Streaming"],["spin_wheel_enabled","Spin Wheel"],["rewarded_ads_enabled","Rewarded Ads"],["feed_ads_enabled","Feed Ads"],["show_download_button","Show Android Download"]];
const AD_FLAGS:[string,string][]=[["daily_login_popup_banner","Daily Login banners"],["engagement_popup_banner","Engagement banners"],["main_feed_banner","Main Feed banner"],["seven_day_banner_enabled","7-Day banner"],["seven_day_playable_enabled","7-Day playable"],["android_native_bridge_enabled","Android native bridge"],["hot_seat_comments_ads_enabled","Hot Seat comments ads"],["hot_seat_questions_ads_enabled","Hot Seat questions ads"],["hot_seat_water_break_ads_enabled","Water Break ads"]];
function Card({children,className=""}:{children:ReactNode;className?:string}){return <section className={"panda-panel rounded-3xl p-4 sm:p-5 "+className}>{children}</section>}
function ToggleRow({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center justify-between gap-3 rounded-2xl border border-border/70 bg-card px-3 py-3 text-sm"><span>{label}</span><Switch checked={value} onCheckedChange={onChange}/></label>}
export function AdminControlCenter(){
 const [tab,setTab]=useState<"overview"|"controls"|"users"|"audit">("overview");
 const [stats,setStats]=useState<Record<string,any>>({}); const [controls,setControls]=useState<Controls|null>(null); const [users,setUsers]=useState<UserRow[]>([]); const [audit,setAudit]=useState<any[]>([]);
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [query,setQuery]=useState(""); const [busy,setBusy]=useState<string|null>(null);
 const load=async()=>{setLoading(true);const [s,c,u,a]=await Promise.all([(supabase as any).rpc("admin_get_dashboard_overview"),(supabase as any).rpc("admin_get_app_control_center"),(supabase as any).rpc("admin_list_users"),(supabase as any).rpc("admin_get_recent_audit",{p_limit:40})]);setLoading(false);const err=s.error||c.error||u.error||a.error;if(err){toast.error(err.message);return;}setStats(s.data??{});setControls(c.data??null);setUsers(u.data??[]);setAudit(a.data??[]);};
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>users.filter(u=>{const q=query.toLowerCase().trim();return !q||u.username?.toLowerCase().includes(q)||u.email?.toLowerCase().includes(q)||u.id.toLowerCase().includes(q)}),[users,query]);
 const setFlag=(section:"app"|"ads"|"crush",key:string,value:any)=>setControls(c=>c?{...c,[section]:{...c[section],[key]:value}}:c);
 const saveControls=async()=>{if(!controls)return;setSaving(true);const {data,error}=await(supabase as any).rpc("admin_save_app_control_center",{p_app:controls.app,p_ads:controls.ads,p_crush:controls.crush});setSaving(false);if(error)return toast.error(error.message);setControls(data);toast.success("Master controls saved");};
 const userAction=async(id:string,action:"ban"|"bc"|"streak")=>{setBusy(id+action);let error:any=null;if(action==="ban"){({error}=await(supabase as any).rpc("admin_toggle_user_ban",{p_user_id:id}))}else if(action==="streak"){({error}=await(supabase as any).rpc("admin_reset_user_streak",{p_user_id:id}))}else {const amount=window.prompt("BC amount to add/remove. Use negative to remove:","0");if(amount===null){setBusy(null);return;}({error}=await(supabase as any).rpc("admin_adjust_user_bc",{p_user_id:id,p_amount:Math.trunc(Number(amount)||0),p_reason:"Admin dashboard adjustment"}));}setBusy(null);if(error){toast.error(error.message);return;}toast.success(action==="ban"?"User status updated":action==="streak"?"Streak reset":"BC balance updated");void load();};
 if(loading)return <Card><div className="grid min-h-32 place-items-center"><Loader2 className="size-7 animate-spin text-primary"/></div></Card>;
 return <div className="space-y-4">
  <Card><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-primary"/><h2 className="font-display text-xl font-black">Master Control Center</h2></div><p className="mt-1 text-xs text-muted-foreground">Users, app switches, monetization controls, operations and admin history — all from one place.</p></div><Button variant="outline" size="sm" onClick={()=>void load()}><RefreshCw className="mr-2 size-3.5"/>Refresh</Button></div>
   <div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-6">
    {[["Users",stats.users,Users],["VIP",stats.vip,ShieldCheck],["Banned",stats.banned,Ban],["BC in wallets",stats.bc_balance,Coins],["Messages 24h",stats.messages_24h,Activity],["Active winners",stats.active_winner_cycles,Gauge]].map(([label,val,Icon])=><div key={String(label)} className="rounded-2xl border border-border/70 bg-card p-3"><Icon className="size-4 text-primary"/><p className="mt-2 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-xl font-black">{Number(val??0).toLocaleString()}</p></div>)}
   </div>
  </Card>
  <div className="flex gap-2 overflow-x-auto">{([["overview",BarChart3,"Overview"],["controls",Gauge,"Controls"],["users",Users,"Users"],["audit",History,"Audit"]] as const).map(([key,Icon,label])=><button key={key} onClick={()=>setTab(key)} className={"shrink-0 rounded-full border px-4 py-2 text-xs font-bold "+(tab===key?"border-primary bg-primary/10 text-primary":"border-border bg-card")}><Icon className="mr-1 inline size-3.5"/>{label}</button>)}</div>
  {tab==="overview"?<div className="grid gap-4 md:grid-cols-2"><Card><h3 className="font-display font-bold">System health</h3><div className="mt-3 space-y-2 text-sm">{[["Registered users",stats.users],["Dating profiles",stats.dating_profiles],["Groups",stats.groups],["Events",stats.events],["Hot Seat scheduled/live",stats.active_hot_seat],["Admin actions 24h",stats.audit_24h]].map(([k,v])=><div key={String(k)} className="flex justify-between rounded-xl bg-secondary/30 px-3 py-2"><span className="text-muted-foreground">{k}</span><b>{Number(v??0).toLocaleString()}</b></div>)}</div></Card><Card><h3 className="font-display font-bold">BC economy</h3><div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-2xl bg-primary/10 p-4"><Coins className="size-4 text-primary"/><p className="mt-2 text-xs text-muted-foreground">Wallet balance</p><p className="text-2xl font-black">{Number(stats.bc_balance??0).toLocaleString()}</p></div><div className="rounded-2xl bg-secondary p-4"><Coins className="size-4"/><p className="mt-2 text-xs text-muted-foreground">Ledger movement 24h</p><p className="text-2xl font-black">{Number(stats.bc_24h??0).toLocaleString()}</p></div></div></Card></div>:null}
  {tab==="controls"&&controls?<><Card><div className="flex items-center justify-between"><div><h3 className="font-display font-bold">App switches</h3><p className="text-xs text-muted-foreground">Emergency on/off controls for major features.</p></div><Button onClick={()=>void saveControls()} disabled={saving}>{saving?<Loader2 className="mr-2 size-4 animate-spin"/>:<Save className="mr-2 size-4"/>}Save all</Button></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{APP_FLAGS.map(([k,l])=><ToggleRow key={k} label={l} value={Boolean(controls.app[k])} onChange={v=>setFlag("app",k,v)}/>)}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Hot Seat mode<input value={controls.app.hot_seat_mode??""} onChange={e=>setFlag("app","hot_seat_mode",e.target.value)} className="mt-1 h-10 w-full rounded-xl border bg-background px-3 text-sm"/></label><label className="text-xs font-semibold">Daily drops<input type="number" min={0} value={controls.app.daily_drops??0} onChange={e=>setFlag("app","daily_drops",Math.max(0,Number(e.target.value)||0))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3 text-sm"/></label><label className="text-xs font-semibold sm:col-span-2">Android download URL<input value={controls.app.apk_url??""} onChange={e=>setFlag("app","apk_url",e.target.value)} className="mt-1 h-10 w-full rounded-xl border bg-background px-3 text-sm"/></label></div></Card>
  <Card><h3 className="font-display font-bold">Ad placement switches</h3><p className="mt-1 text-xs text-muted-foreground">Global switches. Detailed provider routing stays in Universal Ad System.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{AD_FLAGS.map(([k,l])=><ToggleRow key={k} label={l} value={Boolean(controls.ads[k])} onChange={v=>setFlag("ads",k,v)}/>)}</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Feed banner interval<input type="number" min={1} value={controls.ads.feed_banner_interval??1} onChange={e=>setFlag("ads","feed_banner_interval",Math.max(1,Number(e.target.value)||1))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-semibold">Dating/WCW-MCM ad frequency<input type="number" min={1} value={controls.ads.crush_video_frequency??5} onChange={e=>setFlag("ads","crush_video_frequency",Math.max(1,Number(e.target.value)||1))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label></div></Card>
  <Card><h3 className="font-display font-bold">WCW & MCM controls</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><ToggleRow label="WCW/MCM enabled" value={Boolean(controls.crush.enabled)} onChange={v=>setFlag("crush","enabled",v)}/><ToggleRow label="Keep ad in same frame" value={Boolean(controls.crush.ad_same_frame)} onChange={v=>setFlag("crush","ad_same_frame",v)}/></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">MCM release hour<input type="number" min={0} max={23} value={controls.crush.mcm_release_hour??10} onChange={e=>setFlag("crush","mcm_release_hour",Math.max(0,Math.min(23,Number(e.target.value)||0)))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-semibold">WCW release hour<input type="number" min={0} max={23} value={controls.crush.wcw_release_hour??10} onChange={e=>setFlag("crush","wcw_release_hour",Math.max(0,Math.min(23,Number(e.target.value)||0)))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-semibold">Ad every swipes<input type="number" min={1} value={controls.crush.ad_every_swipes??5} onChange={e=>setFlag("crush","ad_every_swipes",Math.max(1,Number(e.target.value)||1))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label></div></Card></>:null}
  {tab==="users"?<Card><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-display font-bold">Panda management</h3><p className="text-xs text-muted-foreground">Search, ban/unban, reset streaks or adjust BC through audited server actions.</p></div><div className="relative w-full sm:w-80"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email or ID" className="h-10 w-full rounded-xl border bg-background pl-9 pr-3 text-sm"/></div></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b text-muted-foreground"><th className="p-2">Panda</th><th className="p-2">Status</th><th className="p-2">BC</th><th className="p-2">XP</th><th className="p-2">Platform</th><th className="p-2">Last active</th><th className="p-2">Actions</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id} className="border-b border-border/50"><td className="p-2"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-full bg-secondary">{u.avatar||"🐼"}</span><div><p className="font-semibold">{u.username}</p><p className="text-[10px] text-muted-foreground">{u.email||u.id.slice(0,8)}</p></div></div></td><td className="p-2"><span className={u.status==="banned"?"text-destructive":"text-primary"}>{u.status}</span></td><td className="p-2">{Number(u.coins||0).toLocaleString()}</td><td className="p-2">{Number(u.reputation||0).toLocaleString()}</td><td className="p-2">{u.platform}</td><td className="p-2">{u.last_active?new Date(u.last_active).toLocaleString():"—"}</td><td className="p-2"><div className="flex gap-1"><Button size="sm" variant="outline" disabled={busy===u.id+"ban"} onClick={()=>void userAction(u.id,"ban")}><Ban className="mr-1 size-3"/>Ban</Button><Button size="sm" variant="outline" disabled={busy===u.id+"bc"} onClick={()=>void userAction(u.id,"bc")}><Coins className="mr-1 size-3"/>BC</Button><Button size="sm" variant="outline" disabled={busy===u.id+"streak"} onClick={()=>void userAction(u.id,"streak")}><Clock3 className="mr-1 size-3"/>Streak</Button></div></td></tr>)}</tbody></table>{filtered.length===0?<div className="py-10 text-center text-sm text-muted-foreground">No users found.</div>:null}</div></Card>:null}
  {tab==="audit"?<Card><div className="flex items-center justify-between"><div><h3 className="font-display font-bold">Admin audit trail</h3><p className="text-xs text-muted-foreground">Recent privileged actions recorded by the server.</p></div><History className="size-5 text-primary"/></div><div className="mt-4 space-y-2">{audit.map((x:any)=><div key={x.id} className="rounded-2xl border border-border/70 bg-card p-3"><div className="flex flex-wrap justify-between gap-2"><b className="text-sm">{x.action}</b><span className="text-[10px] text-muted-foreground">{new Date(x.created_at).toLocaleString()}</span></div><p className="mt-1 text-[10px] text-muted-foreground">{x.target_user_id?"Target: "+x.target_user_id:"System action"}</p>{x.metadata&&Object.keys(x.metadata).length?<pre className="mt-2 overflow-auto rounded-xl bg-secondary/40 p-2 text-[10px]">{JSON.stringify(x.metadata,null,2)}</pre>:null}</div>)}{audit.length===0?<p className="py-8 text-center text-sm text-muted-foreground">No audit records yet.</p>:null}</div></Card>:null}
 </div>
}