import { useEffect, useState } from "react";
import { Eye, Loader2, Send, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

type Target={id:string;name:string;kind:"group"|"vip";subtitle?:string};

export function AdminGroupMediaManager(){
 const [targets,setTargets]=useState<Target[]>([]),[targetId,setTargetId]=useState(""),[targetKind,setTargetKind]=useState<"group"|"vip">("group"),[file,setFile]=useState<File|null>(null),[viewOnce,setViewOnce]=useState(true),[sending,setSending]=useState(false),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const {data,error}=await(supabase as any).rpc("admin_list_group_media_targets");setLoading(false);if(error)return toast.error(error.message??"Could not load group targets");const rows=(data??[]) as Target[];setTargets(rows);if(!targetId&&rows[0]){setTargetId(rows[0].id);setTargetKind(rows[0].kind)}};
 useEffect(()=>{void load()},[]);
 const send=async()=>{if(!file||!targetId)return toast.error("Choose a group and media first");const type=file.type.startsWith("image/")?"image":file.type.startsWith("video/")?"video":file.type.startsWith("audio/")?"audio":null;if(!type)return toast.error("Choose an image, video or audio file");if(file.size>25*1024*1024)return toast.error("Media must be 25 MB or smaller");setSending(true);try{const uid=(await supabase.auth.getUser()).data.user?.id;if(!uid)throw new Error("Authentication required");const ext=file.name.split(".").pop()?.toLowerCase()||(type==="image"?"jpg":type==="video"?"mp4":"webm");const path=`admin/${uid}/${targetId}/${crypto.randomUUID()}.${ext}`;const bucket="circle-panda-group-media";const upload=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false});if(upload.error)throw upload.error;const {error}=await(supabase as any).rpc("admin_send_group_media_secure",{p_group_id:targetId,p_is_vip:targetKind==="vip",p_message_type:type,p_media_path:path,p_mime_type:file.type||null,p_duration_seconds:null,p_view_once:type!=="audio"&&viewOnce,p_body:""});if(error){await supabase.storage.from(bucket).remove([path]);throw error}setFile(null);toast.success(`${targetKind==="vip"?"VIP":"Group"} media sent`)}catch(e:any){toast.error(e?.message??"Media could not be sent")}finally{setSending(false)}};
 return <section className="panda-panel rounded-3xl p-4 sm:p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-display text-lg font-black">Group Media Control</h2><p className="mt-1 text-xs text-muted-foreground">Send photos, videos or audio directly into a normal or VIP group. View Once is enforced by the server.</p></div><Upload className="size-5 text-primary"/></div>{loading?<div className="grid min-h-24 place-items-center"><Loader2 className="size-5 animate-spin"/></div>:<div className="mt-4 grid gap-3"><label className="text-xs font-semibold">Destination<select value={targetId?`${targetKind}:${targetId}`:""} onChange={e=>{const [kind,id]=e.target.value.split(":");setTargetKind(kind as "group"|"vip");setTargetId(id)}} className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"><option value="">Choose a destination</option>{targets.map(t=><option key={`${t.kind}:${t.id}`} value={`${t.kind}:${t.id}`}>{t.kind==="vip"?"VIP · ":"Group · "}{t.name}{t.subtitle?` — ${t.subtitle}`:""}</option>)}</select></label><label className="text-xs font-semibold">Media file<input type="file" accept="image/*,video/*,audio/*" className="mt-1 block w-full rounded-xl border bg-background p-2 text-sm" onChange={e=>setFile(e.target.files?.[0]??null)}/></label><label className="flex items-center justify-between rounded-xl border bg-background px-3 py-3 text-xs font-semibold"><span className="flex items-center gap-2"><Eye className="size-4"/>View Once <span className="font-normal text-muted-foreground">(photos/videos)</span></span><Switch checked={viewOnce} onCheckedChange={setViewOnce}/></label><Button onClick={()=>void send()} disabled={sending||!file||!targetId}><Send className="mr-2 size-4"/>{sending?"Sending…":"Send to group"}</Button></div>}</section>
}