import { useEffect, useState } from "react";
import { Loader2, Trophy, Search, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
type Activity={id:string;title:string;activity_type:string}; type Profile={id:string;display_name:string;avatar_url:string|null};
export function UniversalWinnerManager(){
const [activities,setActivities]=useState<Activity[]>([]),[profiles,setProfiles]=useState<Profile[]>([]),[activityId,setActivityId]=useState(""),[activityKey,setActivityKey]=useState(""),[title,setTitle]=useState(""),[prize,setPrize]=useState(""),[start,setStart]=useState(""),[end,setEnd]=useState(""),[mode,setMode]=useState<"random"|"weighted"|"manual">("weighted"),[manual,setManual]=useState(""),[search,setSearch]=useState(""),[saving,setSaving]=useState(false),[maxAttempts,setMaxAttempts]=useState(1),[entryLimit,setEntryLimit]=useState(""),[completionBC,setCompletionBC]=useState(0),[completionXP,setCompletionXP]=useState(0),[winnerBC,setWinnerBC]=useState(0),[winnerXP,setWinnerXP]=useState(0),[badge,setBadge]=useState("");
useEffect(()=>{void(async()=>{const [{data:a},{data:p}]=await Promise.all([(supabase as any).from("activities").select("id,title,activity_type").eq("is_enabled",true).order("sort_order"),(supabase as any).from("profiles").select("id,display_name,avatar_url").order("display_name").limit(200)]);setActivities(a??[]);setProfiles(p??[])})()},[]);
const create=async()=>{if(!activityKey||!title||!prize||!start||!end)return toast.error("Fill the activity, title, prize, start and end time.");if(mode==="manual"&&!manual)return toast.error("Select the manual winner.");setSaving(true);const {error}=await(supabase as any).rpc("cp_start_winner_cycle",{p_scope:"global",p_activity_id:activityId||null,p_activity_key:activityKey.trim(),p_title:title.trim(),p_prize:prize.trim(),p_starts_at:new Date(start).toISOString(),p_ends_at:new Date(end).toISOString(),p_winner_mode:mode,p_xp_weight:.5,p_activity_weight:.5,p_manual_winner_id:manual||null,p_max_attempts:maxAttempts,p_entry_limit:entryLimit?Math.max(1,Number(entryLimit)):null,p_eligibility:{},p_completion_reward_bc:completionBC,p_completion_reward_xp:completionXP,p_winner_reward_bc:winnerBC,p_winner_reward_xp:winnerXP,p_winner_badge:badge.trim()||null});setSaving(false);if(error)return toast.error(error.message);toast.success("Winner activity scheduled.")};
const matches=profiles.filter(p=>p.display_name.toLowerCase().includes(search.toLowerCase())).slice(0,8);
return <section className="panda-panel rounded-3xl p-4 sm:p-5"><div className="flex items-center gap-2"><Trophy className="size-4 text-amber-400"/><h2 className="font-display font-bold">Universal Activity Engine</h2></div><p className="mt-1 text-xs text-muted-foreground">Admin can select a specific winner for any activity. Spin the Wheel and Water Break are explicit activity targets.</p><p className="mt-1 text-xs text-muted-foreground">Previous winner → activity → server cutoff → automatic rewards → winner announcement. Users never need to be online together.</p>
<div className="mt-4 grid gap-3 sm:grid-cols-2">
<label className="text-xs font-semibold">Activity<select value={activityId} onChange={e=>{const value=e.target.value;const a=activities.find(x=>x.id===value);setActivityId(value);if(value==="__wheel_spin"){setActivityKey("wheel_spin");setTitle("Spin the Wheel");}else if(value==="__water_break"){setActivityKey("water_break");setTitle("Water Break");}else if(value==="__global"){setActivityKey("global");setTitle("Global Activity");}else{setActivityKey(a?.activity_type??"");setTitle(a?.title??"")}}} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="">Global/custom activity</option><option value="__wheel_spin">🎡 Spin the Wheel</option><option value="__water_break">💧 Water Break Activities</option><option value="__global">🌐 All Activities / Global Winner</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>
<label className="text-xs font-semibold">Activity key<input value={activityKey} onChange={e=>setActivityKey(e.target.value)} placeholder="coin-drop / giveaway / global" className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label>
<label className="text-xs font-semibold">Title<input value={title} onChange={e=>setTitle(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label><label className="text-xs font-semibold">Prize<input value={prize} onChange={e=>setPrize(e.target.value)} placeholder="500 BC / Prize name" className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label>
<label className="text-xs font-semibold">Starts<input type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label><label className="text-xs font-semibold">Server cutoff<input type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label>
<label className="text-xs font-semibold">Winner selection<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)} className="mt-1 h-11 w-full rounded-xl border bg-background px-3"><option value="weighted">XP + activity weighted</option><option value="random">Random eligible</option><option value="manual">Manual admin selection</option></select></label><label className="text-xs font-semibold">Attempts per Panda<input type="number" min={1} max={100} value={maxAttempts} onChange={e=>setMaxAttempts(Math.max(1,Math.min(100,Number(e.target.value)||1)))} className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label>
<label className="text-xs font-semibold">Total entry limit<input type="number" min={1} value={entryLimit} onChange={e=>setEntryLimit(e.target.value)} placeholder="Unlimited" className="mt-1 h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label>
<div className="text-xs font-semibold"><span>Manual winner</span><div className="relative mt-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search Panda name" className="h-11 w-full rounded-xl border bg-background pl-9 pr-3 text-sm"/></div>{search&&mode==="manual"?<div className="mt-1 max-h-36 overflow-auto rounded-xl border bg-card">{matches.map(p=><button key={p.id} onClick={()=>{setManual(p.id);setSearch(p.display_name)}} className="flex w-full items-center gap-2 p-2 text-left text-xs hover:bg-secondary">{p.avatar_url?<img src={p.avatar_url} className="size-7 rounded-full" alt=""/>:<span className="size-7 rounded-full bg-secondary"/>}<span>{p.display_name}</span></button>)}</div>:null}</div></div>
<div className="mt-4 rounded-2xl border border-primary/20 bg-primary/5 p-3"><div className="flex items-center gap-2 text-xs font-bold"><Settings2 className="size-4"/>Automatic rewards</div><div className="mt-3 grid gap-3 sm:grid-cols-4">
<label className="text-xs font-semibold">Completion BC<input type="number" min={0} value={completionBC} onChange={e=>setCompletionBC(Math.max(0,Number(e.target.value)||0))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-semibold">Completion XP<input type="number" min={0} value={completionXP} onChange={e=>setCompletionXP(Math.max(0,Number(e.target.value)||0))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-semibold">Winner BC<input type="number" min={0} value={winnerBC} onChange={e=>setWinnerBC(Math.max(0,Number(e.target.value)||0))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-semibold">Winner XP<input type="number" min={0} value={winnerXP} onChange={e=>setWinnerXP(Math.max(0,Number(e.target.value)||0))} className="mt-1 h-10 w-full rounded-xl border bg-background px-3"/></label>
<label className="text-xs font-semibold sm:col-span-2">Winner badge<input value={badge} onChange={e=>setBadge(e.target.value)} maxLength={60} placeholder="Optional badge name" className="mt-1 h-10 w-full rounded-xl border bg-background px-3 text-sm"/></label></div></div>
<div className="mt-4 rounded-2xl border border-amber-500/20 bg-amber-500/5 p-3 text-xs"><b>Server guarantees:</b> cutoff, attempts, one-time completion reward, winner reward and previous-winner chaining are handled on the server.</div><Button className="mt-4" onClick={()=>void create()} disabled={saving}>{saving?<Loader2 className="mr-2 size-4 animate-spin"/>:null}Schedule activity</Button></section>;}
