import { useEffect, useState, type MouseEvent } from "react";
import { Check, ChevronLeft, Gift, Loader2, Play, Sparkles, Target as TargetIcon, Trophy, X } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { useActiveAdCreative } from "@/components/ads/adInventoryStorage";
import { notifyAdEvent, openAdExternalUrl } from "@/components/ads/platformAdBridge";
import { supabase } from "@/integrations/supabase/client";
import { useStore } from "@/lib/store";

const GAMES = [
  { slug:"wheel_spin", title:"Lucky Wheel", icon:"🎡", description:"Spin the glowing Circle Panda wheel and reveal your reward." },
  { slug:"mystery_box", title:"Mystery Box", icon:"🎁", description:"Choose one glowing box and watch it open to reveal your prize." },
  { slug:"target", title:"Panda Target", icon:"🎯", description:"Hit Panda's neon target as accurately as you can." },
  { slug:"cup_shuffle", title:"Panda Cup Shuffle", icon:"🥤", description:"Pick a prize, then watch Panda flip, mix and shuffle the cups before the reveal." },
  { slug:"puzzle", title:"Panda Puzzle", icon:"🧩", description:"Solve a quick Panda puzzle to unlock your reward." },
  { slug:"coin_drop", title:"Coin Drop", icon:"🪙", description:"Catch falling coins for 60 seconds. Stones cost 3 BC." },
  { slug:"slots", title:"Panda Slots", icon:"🎰", description:"Play the neon reels for 60 seconds, then watch the calculating reveal." },
  { slug:"lucky_card", title:"Lucky Card", icon:"🃏", description:"Choose a glowing card and reveal the hidden reward." },
  { slug:"secret_reveal", title:"Secret Reveal", icon:"🕵️", description:"Solve a real Secret Confession puzzle, then choose whether to reveal it." },
  { slug:"playable_ad", title:"Just Playbo Ads", icon:"▶️", description:"Sponsored experience only. No BC reward." },
] as const;

type Result = { result?:string; reward_bc?:number; reward_label?:string; attempts_left?:number; ad_required?:boolean; sponsor?:string; detail?:string; secret?:string } | null;

function Banner({ className="" }:{placement:"seven_day_banner";className?:string}) {
  const ad=useActiveAdCreative("seven_day_banner");
  useEffect(()=>{if(ad) void notifyAdEvent("impression",{adId:ad.id,format:ad.videoUrl?"video":"banner"});},[ad]);
  if(!ad) return null;
  return <button type="button" onClick={()=>{void notifyAdEvent("click",{adId:ad.id,format:ad.videoUrl?"video":"banner"});openAdExternalUrl(ad.destinationUrl,ad.sponsor);}} className={"w-full rounded-2xl border border-border/70 bg-card p-3 text-left shadow-sm "+className}>
    <div className="flex items-center justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-1.5 text-[9px] font-bold uppercase tracking-wider text-muted-foreground"><span className="rounded bg-muted px-1.5 py-0.5 text-foreground">Sponsored</span><span className="truncate">{ad.sponsor}</span></div><p className="mt-1 truncate text-xs font-semibold">{ad.headline}</p></div><span className="shrink-0 rounded-xl bg-primary/10 px-3 py-2 text-[10px] font-bold text-primary">{ad.callToAction||"Explore"}</span></div>
  </button>;
}

function PlayableGate({surface,onComplete,onClose,required=true}:{surface:string;onComplete:(id?:string)=>void;onClose:()=>void;required?:boolean}) {
  const ad=useActiveAdCreative("seven_day_playable");
  const [sessionId,setSessionId]=useState<string|null>(null),[started,setStarted]=useState(false),[done,setDone]=useState(false),[seconds,setSeconds]=useState(0),[busy,setBusy]=useState(false);
  useEffect(()=>{if(!started||!ad?.durationSeconds)return;const id=window.setInterval(()=>setSeconds(v=>Math.min(v+1,ad.durationSeconds??8)),1000);return()=>window.clearInterval(id);},[started,ad?.durationSeconds]);
  const start=async()=>{if(!ad?.id)return toast.info("No sponsored playable is active right now.");setBusy(true);const {data,error}=await (supabase as any).rpc("start_rewarded_ad_session",{p_ad_id:ad.id,p_surface:surface});setBusy(false);if(error)return toast.error(error.message??"Sponsored playable could not start");setSessionId(data?.session_id??null);setStarted(true);setSeconds(0);void notifyAdEvent("impression",{adId:ad.id,format:"rewarded"});};
  const complete=async()=>{if(!sessionId)return;setBusy(true);const {data,error}=await (supabase as any).rpc("complete_rewarded_ad_session",{p_session_id:sessionId});if(error){setBusy(false);return toast.error(error.message??"Finish the sponsored playable first");}if(surface==="seven_day_playable_only"){const {error:activityError}=await (supabase as any).rpc("play_seven_day_activity",{p_slug:"playable_ad",p_action:"playable_complete",p_payload:{session_id:sessionId}});if(activityError){setBusy(false);return toast.error(activityError.message??"Playable activity could not be completed");}}setBusy(false);setDone(true);onComplete(sessionId);if(Number(data?.reward_bc??0)>0)toast.success("Sponsored ad reward +"+data.reward_bc+" BC");};
  if(!ad)return <div className="cp-sponsored-card"><span>SPONSORED</span><p>No direct sponsor creative is active.</p><small>On Android, the native AdMob bridge can supply the ad.</small></div>;
  return <div className="cp-playable-gate"><div className="cp-playable-head"><span>Sponsored / AdMob</span><button type="button" onClick={onClose}><X className="size-3.5"/></button></div>
    {ad.videoUrl?<video src={ad.videoUrl} poster={ad.posterUrl||ad.imageUrl} controls playsInline muted className="cp-playable-video" onPlay={()=>setStarted(true)} onEnded={()=>setSeconds(ad.durationSeconds??8)}/>:<div className="cp-sponsored-card"><span>DIRECT SPONSOR</span><p>{ad.headline}</p><div className="cp-sponsor-mark">AD</div></div>}
    <div className="cp-playable-copy"><p>{ad.headline}</p><span>{ad.description||ad.tagline||"Sponsored experience"}</span></div>
    {!started?<Button className="w-full" onClick={()=>void start()} disabled={busy}>{busy?<Loader2 className="size-4 animate-spin"/>:<Play className="size-4"/>} Start sponsored playable</Button>:<Button className="w-full" onClick={()=>void complete()} disabled={busy||done||seconds<Math.max(1,(ad.durationSeconds??8)-1)}>{busy?<Loader2 className="size-4 animate-spin"/>:done?<Check className="size-4"/>:<Gift className="size-4"/>}{done?"Completed":"Complete playable ("+Math.max(0,(ad.durationSeconds??8)-seconds)+"s)"}</Button>}
    {!required&&<Button variant="ghost" className="w-full" onClick={onClose}>Skip</Button>}
  </div>;
}

export function SevenDayActivitiesModal({open,onClose,onComplete}:{open:boolean;onClose:()=>void;onComplete?:()=>void}) {
  const {syncCoins}=useStore();
  const [activity,setActivity]=useState<any>(null),[dayNumber,setDayNumber]=useState<number|null>(null),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<Result>(null),[adFor,setAdFor]=useState<{slug:string;mode:"extra"|"required"}|null>(null),[timer,setTimer]=useState(0),[coinScore,setCoinScore]=useState(0),[coinStones,setCoinStones]=useState(0),[targetPoint,setTargetPoint]=useState<{x:number;y:number}|null>(null),[puzzleAnswer,setPuzzleAnswer]=useState(""),[puzzleQuestion,setPuzzleQuestion]=useState("Solve today's puzzle."),[sponsorChoices,setSponsorChoices]=useState<{key:number;sponsor:string}[]>([]),[secretPieces,setSecretPieces]=useState<string[]>([]),[secretAnswer,setSecretAnswer]=useState<string[]>([]),[secretChoice,setSecretChoice]=useState<"yes"|"no"|null>(null),[completed,setCompleted]=useState(false),[cardPhase,setCardPhase]=useState<"idle"|"mixing"|"ready"|"flipping"|"revealed">("idle"),[cupPhase,setCupPhase]=useState<"idle"|"placing"|"shuffling"|"revealed">("idle"),[cupPrize,setCupPrize]=useState<string>("");
  const gameMeta=GAMES.find(g=>g.slug===activity?.slug);
  const attemptLeft=Number(activity?.attempts_left??0);

  const load=async()=>{setLoading(true);const {data,error}=await (supabase as any).rpc("get_today_seven_day_activity");setLoading(false);if(error)return toast.error(error.message??"Today's activity could not load");const a=data?.available?data.activity:null;setDayNumber(Number(data?.day_number??0));setActivity(a);setCompleted(Boolean(a?.completed)&&Number(a?.attempts_left??0)<=0);setPuzzleQuestion(String(a?.puzzle_question||"Solve today's puzzle."));};
  useEffect(()=>{if(open){setResult(null);setAdFor(null);setTimer(0);setCoinScore(0);setCoinStones(0);setTargetPoint(null);setPuzzleAnswer("");setSecretPieces([]);setSecretAnswer([]);setSecretChoice(null);setCompleted(false);setSponsorChoices([]);setCardPhase("idle");setCupPhase("idle");setCupPrize("");void load();}},[open]);

  const finish=()=>{setCompleted(true);toast.success("Today's activity is complete.");onComplete?.();};
  const play=async(action="play",payload:Record<string,unknown>={})=>{if(!activity)return;setBusy(true);setResult(null);const {data,error}=await (supabase as any).rpc("play_seven_day_activity",{p_slug:activity.slug,p_action:action,p_payload:payload});setBusy(false);if(error)return toast.error(error.message??"Activity could not be completed");setResult(data as Result);setActivity((a:any)=>a?({...a,attempts_left:Number(data?.attempts_left??a.attempts_left)}):a);if(activity.slug==="cup_shuffle"&&["revealed","completed"].includes(String(data?.result)))setCupPhase("revealed");if(Number(data?.reward_bc??0)!==0){await syncCoins();toast.success((data?.reward_label||"Reward")+" · "+(data.reward_bc>0?"+":"")+data.reward_bc+" BC");}if(data?.ad_required)setAdFor({slug:activity.slug,mode:"required"});else if(["revealed","solved","completed"].includes(String(data?.result)))finish();};

  const startTimed=async()=>{const seconds=Number(activity?.timer_seconds??60);const {data,error}=await (supabase as any).rpc("play_seven_day_activity",{p_slug:activity.slug,p_action:"start",p_payload:{}});if(error)return toast.error(error.message??"Activity could not start");setResult(data as Result);setActivity((a:any)=>a?({...a,attempts_left:Number(data?.attempts_left??a.attempts_left)}):a);setTimer(seconds);setCoinScore(0);setCoinStones(0);};
  useEffect(()=>{if(timer<=0)return;const id=window.setInterval(()=>setTimer(v=>v-1),1000);return()=>window.clearInterval(id);},[timer]);
  useEffect(()=>{if(timer!==0)return;if(activity?.slug!=="coin_drop"&&activity?.slug!=="slots")return;if(result?.result!=="running")return;const id=window.setTimeout(()=>void play("finish"),activity.slug==="coin_drop"?1100:1500);return()=>window.clearTimeout(id);},[timer,activity?.slug,result?.result]);

  const loadSponsors=async()=>{const {data,error}=await (supabase as any).rpc("play_seven_day_activity",{p_slug:"guess_sponsor",p_action:"options",p_payload:{}});if(error)return toast.error(error.message??"Sponsor choices could not load");setSponsorChoices((data?.choices??[]) as {key:number;sponsor:string}[]);};
  useEffect(()=>{if(open&&activity?.slug==="guess_sponsor")void loadSponsors();},[open,activity?.slug]);

  const startTarget=async()=>{setBusy(true);const {data,error}=await (supabase as any).rpc("play_seven_day_activity",{p_slug:"target",p_action:"start",p_payload:{}});setBusy(false);if(error)return toast.error(error.message??"Target could not start");setTargetPoint({x:Number(data?.target_x??50),y:Number(data?.target_y??50)});setActivity((a:any)=>a?({...a,attempts_left:Number(data?.attempts_left??a.attempts_left)}):a);};
  const fireTarget=async(e:MouseEvent<HTMLDivElement>)=>{if(!targetPoint||busy)return;const r=e.currentTarget.getBoundingClientRect();await play("target",{x:((e.clientX-r.left)/r.width)*100,y:((e.clientY-r.top)/r.height)*100});setTargetPoint(null);};

  const startLuckyCard=async()=>{setBusy(true);const {data,error}=await (supabase as any).rpc("play_lucky_card",{p_action:"start"});setBusy(false);if(error)return toast.error(error.message??"Lucky Card could not start");setResult(data as Result);setActivity((a:any)=>a?({...a,attempts_left:Number(data?.attempts_left??a.attempts_left)}):a);};
  const revealLuckyCard=async(card:number)=>{setBusy(true);const {data,error}=await (supabase as any).rpc("play_lucky_card",{p_action:"reveal",p_card:card});setBusy(false);if(error)return toast.error(error.message??"Lucky Card could not reveal");setResult(data as Result);if(Number(data?.reward_bc??0)!==0){await syncCoins();toast.success((data?.reward_label||"Reward")+" · +"+data.reward_bc+" BC");}setCardPhase("revealed");finish();};

  const startSecret=async()=>{setBusy(true);const {data,error}=await (supabase as any).rpc("play_secret_reveal",{p_action:"start",p_words:[]});setBusy(false);if(error)return toast.error(error.message??"Secret puzzle could not start");setSecretPieces((data?.pieces??[]) as string[]);setSecretAnswer([]);setResult(data as Result);setActivity((a:any)=>a?({...a,attempts_left:Number(data?.attempts_left??a.attempts_left)}):a);};
  const solveSecret=async()=>{if(!secretAnswer.length)return toast.error("Put the secret together first.");setBusy(true);const {data,error}=await (supabase as any).rpc("play_secret_reveal",{p_action:"solve",p_words:secretAnswer});setBusy(false);if(error)return toast.error(error.message??"Secret puzzle could not be checked");setResult(data as Result);if(Number(data?.reward_bc??0)!==0){await syncCoins();toast.success((data?.reward_label||"Reward")+" · +"+data.reward_bc+" BC");}if(data?.ad_required)setAdFor({slug:"secret_reveal",mode:"required"});};
  const chooseSecret=async(choice:"yes"|"no")=>{setSecretChoice(choice);setBusy(true);const {data,error}=await (supabase as any).rpc("play_secret_reveal",{p_action:"choice",p_words:[choice]});setBusy(false);if(error)return toast.error(error.message??"Secret choice could not be completed");setResult(data as Result);finish();};

  const hasResult=Boolean(result&&result.result!=="running");
  const luckyCards=[0,1,2];
  return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="cp-game-dialog max-h-[96vh] w-[94vw] max-w-md overflow-y-auto rounded-[28px] border-0 p-0">
    <div className="cp-game-shell">
      <div className="cp-game-topbar"><button type="button" onClick={onClose} className="cp-icon-button"><ChevronLeft className="size-5"/></button><div className="min-w-0 text-center"><DialogTitle className="cp-game-title">{gameMeta?.title||activity?.title||"Today's Activity"}</DialogTitle><DialogDescription className="cp-game-subtitle">Day {dayNumber??"—"} · {attemptLeft} attempt{attemptLeft===1?"":"s"} left</DialogDescription></div><div className="cp-panda-orb">🐼</div></div>
      {loading?<div className="cp-game-loading"><Loader2 className="size-9 animate-spin"/><span>Loading today's activity…</span></div>:!activity?<div className="cp-empty-state"><Gift className="mx-auto size-10"/><h2>No activity today</h2><p>Circle Panda Admin has not scheduled an activity for today.</p></div>:<>
        <div className="cp-game-hero"><div className="cp-game-badge">{gameMeta?.icon}</div><div className="min-w-0 flex-1"><p className="cp-eyebrow">TODAY'S ACTIVITY</p><h2>{activity.title}</h2><p>{activity.description}</p></div></div>

        {activity.slug==="wheel_spin"&&<><div className="cp-game-card cp-wheel-game"><div className="cp-status-pill"><Sparkles className="size-3"/> {attemptLeft} Free Spin{attemptLeft===1?"":"s"}</div><div className="cp-wheel-wrap"><div className="cp-wheel-pointer"/><div className={"cp-neon-wheel "+(busy?"is-spinning":"")}><div className="cp-wheel-center">SPIN</div><span>🪙</span><span>🎁</span><span>💎</span><span>⭐</span><span>🪙</span><span>🎟️</span><span>🏆</span><span>🎁</span></div></div><Button className="cp-neon-button cp-big-button" disabled={busy||attemptLeft<=0||completed} onClick={()=>void play()}>SPIN NOW</Button></div><Banner placement="seven_day_banner" className="cp-ad-banner"/></>}

        {activity.slug==="mystery_box"&&<div className="cp-game-card"><div className="cp-section-label">CHOOSE ONE BOX</div><div className="cp-box-grid">{[0,1,2].map(box=><button key={box} type="button" disabled={busy||attemptLeft<=0||completed||hasResult} onClick={()=>void play("play",{box})} className="cp-mystery-box"><span className="cp-box-lid"/><span className="cp-box-bow">✦</span><span className="cp-box-question">?</span><small>BOX {box+1}</small></button>)}</div><p className="cp-helper">Pick one box. Opening and reveal animation comes before the reward.</p></div>}

        {activity.slug==="target"&&<div className="cp-game-card"><div className="cp-section-label">PANDA TARGET</div><div onClick={fireTarget} className="cp-target-stage"><div className="cp-target-ring ring-one"/><div className="cp-target-ring ring-two"/><div className="cp-target-ring ring-three"/><div className="cp-target-bullseye"/>{targetPoint?<button type="button" className="cp-target-pin" style={{left:targetPoint.x+"%",top:targetPoint.y+"%"}}><TargetIcon className="size-5"/></button>:<TargetIcon className="cp-target-icon"/>}</div><p className="cp-game-instruction">{targetPoint?"Tap the target to fire":"Start the challenge to reveal Panda's target."}</p><Button className="cp-neon-button cp-big-button" disabled={busy||attemptLeft<=0||completed||Boolean(targetPoint)} onClick={startTarget}>{targetPoint?"FIRE":"START TARGET"}</Button></div>}

        {activity.slug==="cup_shuffle"&&<div className="cp-game-card cp-cup-game">
  <div className="cp-section-label">PANDA CUP SHUFFLE</div>
  {cupPhase==="idle"&&<><p className="cp-question">Pick the prize you want Panda to hide.</p><div className="cp-prize-grid cp-prize-grid-three">{["💎 Crystal Prize","🎁 Mystery Gift","🪙 BC Jackpot"].map((p,i)=><button key={p} type="button" disabled={busy||attemptLeft<=0||completed} className="cp-prize-choice" onClick={()=>{setCupPrize(p);setCupPhase("placing");window.setTimeout(()=>setCupPhase("shuffling"),650);window.setTimeout(()=>void play("play",{prize:p}),1850);}}><span>{["💎","🎁","🪙"][i]}</span><small>{p.split(" ").slice(1).join(" ")}</small></button>)}</div></>}
  {cupPhase!=="idle"&&<div className={"cp-cup-stage "+(cupPhase==="shuffling"?"is-shuffling":"")}>
    <div className="cp-cup-glow"/><div className="cp-cup-prize">{cupPhase==="placing"||cupPhase==="shuffling"?cupPrize.split(" ")[0]:"✨"}</div>
    <div className="cp-panda-hand cp-hand-left">🐼</div><div className="cp-panda-hand cp-hand-right">✋</div>
    <div className="cp-cups-row">{[0,1,2].map(i=><div key={i} className={"cp-cup-wrap cup-"+i}><div className="cp-cup-shadow"/><div className="cp-cup">🥤</div><div className="cp-cup-highlight"/></div>)}</div>
    <div className="cp-shuffle-label">{cupPhase==="placing"?"Panda is placing your prize…":cupPhase==="shuffling"?"Panda is mixing the cups…":"SHUFFLE COMPLETE"}</div>
  </div>}
  {hasResult&&<div className="cp-cup-reveal"><span>✨</span><strong>{result?.reward_label||"Prize Revealed"}</strong><b>{Number(result?.reward_bc||0)>0?"+"+result?.reward_bc+" BC":""}</b></div>}
</div>}

        {activity.slug==="puzzle"&&<><div className="cp-game-card"><div className="cp-puzzle-art"><div className="cp-puzzle-piece">✦</div><div className="cp-puzzle-piece">?</div><div className="cp-puzzle-piece">★</div><div className="cp-puzzle-piece">✦</div></div><div className="cp-section-label">PANDA PUZZLE</div><p className="cp-question">{puzzleQuestion}</p><input value={puzzleAnswer} onChange={e=>setPuzzleAnswer(e.target.value)} placeholder="Type your answer" className="cp-game-input"/><Button className="cp-neon-button cp-big-button" disabled={busy||attemptLeft<=0||!puzzleAnswer.trim()||completed} onClick={()=>void play("solve",{answer:puzzleAnswer.trim().toLowerCase()})}>SUBMIT PUZZLE</Button></div><Banner placement="seven_day_banner" className="cp-ad-banner"/></>}

        {activity.slug==="coin_drop"&&<div className="cp-game-card cp-coin-game"><div className="cp-sponsored-strip"><span>Sponsored Banner</span><b>YOUR AD HERE</b></div><div className="cp-coin-timer">00:{String(timer).padStart(2,"0")}</div><div className="cp-coin-rain">{Array.from({length:12},(_,i)=><span key={i} style={{left:(8+(i*31)%86)+"%",animationDelay:(i%6)*.18+"s"}}>🪙</span>)}</div><div className="cp-coin-panda">🐼</div><p className="cp-game-instruction">{timer>0?"Tap the falling coins!":result?.result==="running"?"Revealing your result…":"60 seconds of Coin Drop"}</p>{timer>0&&<button type="button" className="cp-coin-tap" onClick={async()=>{const {data,error}=await (supabase as any).rpc("play_seven_day_activity",{p_slug:"coin_drop",p_action:"drop",p_payload:{}});if(error)toast.error(error.message??"Drop failed");else{setCoinScore(Number(data?.score??0));setCoinStones(Number(data?.stones??0));}}}>🪙</button>}<div className="cp-stat-row"><span>TIME<b>{timer}s</b></span><span>COINS<b>{coinScore}</b></span><span>STONES<b>{coinStones}</b></span></div><Button className="cp-neon-button cp-big-button" disabled={busy||attemptLeft<=0||timer>0||completed} onClick={()=>void startTimed()}>START DROP</Button></div>}

        {activity.slug==="slots"&&<div className="cp-game-card cp-slots-game"><Banner placement="seven_day_banner" className="cp-ad-banner cp-ad-top"/><div className="cp-slots-lights">✦ ✦ ✦ ✦ ✦</div><div className="cp-slots-timer">00:{String(timer).padStart(2,"0")}</div><div className="cp-reels"><div>🍒</div><div>🪙</div><div>🎁</div></div><p className="cp-game-instruction">{timer>0?"SPINNING…":result?.result==="running"?"CALCULATING…":"Ready for your spin?"}</p><Button className="cp-neon-button cp-big-button" disabled={busy||attemptLeft<=0||timer>0||completed} onClick={()=>void startTimed()}>SPIN</Button></div>}

        {activity.slug==="lucky_card"&&<div className="cp-game-card cp-card-game">
  <div className="cp-section-label">LUCKY CARD</div>
  <p className="cp-question">{cardPhase==="idle"?"Panda is ready to mix the cards.":cardPhase==="mixing"?"Panda is mixing the cards…":cardPhase==="ready"?"Choose one card.":cardPhase==="flipping"?"Panda is flipping your card…":"Your card is revealed!"}</p>
  <div className={"cp-card-table "+(cardPhase==="mixing"?"is-mixing":"")}>
    <div className="cp-card-panda-hand">🐼✋</div>
    <div className="cp-card-fan">{luckyCards.map(i=><button key={i} type="button" disabled={busy||completed||cardPhase==="idle"||cardPhase==="mixing"||cardPhase==="flipping"||cardPhase==="revealed"} onClick={()=>{setCardPhase("flipping");window.setTimeout(()=>void revealLuckyCard(i),900)}} className={"cp-real-card card-"+i+" "+(cardPhase==="flipping"?"is-flipping":"")}><span className="cp-card-back">✦<small>CIRCLE PANDA</small></span><span className="cp-card-front"><b>{["💎","🎁","🪙"][i]}</b><small>{result?.reward_label||"LUCKY"}</small></span></button>)}</div>
  </div>
  {cardPhase==="idle"&&<Button className="cp-neon-button cp-big-button" disabled={busy||attemptLeft<=0||completed} onClick={()=>{setCardPhase("mixing");window.setTimeout(()=>{void startLuckyCard();setCardPhase("ready")},1450)}}>MIX THE CARDS</Button>}
  {cardPhase==="ready"&&<div className="cp-card-hint">Tap a card to flip it.</div>}
  {cardPhase==="revealed"&&<div className="cp-cup-reveal"><span>✨</span><strong>{result?.reward_label||"Reward Revealed"}</strong><b>+{result?.reward_bc||0} BC</b></div>}
  <Banner placement="seven_day_banner" className="cp-ad-banner"/></div>}

        {activity.slug==="secret_reveal"&&<div className="cp-game-card cp-secret-game"><div className="cp-secret-art"><div>🐼</div><span>?</span><span>?</span><span>?</span></div>{!secretPieces.length?<><p className="cp-question">Reconstruct today's real Secret Confession.</p><Button className="cp-neon-button cp-big-button" onClick={()=>void startSecret()} disabled={busy||completed||attemptLeft<=0}>START SECRET PUZZLE</Button></>:<><div className="cp-secret-timer">45s</div><p className="cp-section-label">PUT THE SECRET TOGETHER</p><div className="cp-secret-answer">{secretAnswer.length?secretAnswer.map((w,i)=><button key={i} type="button" onClick={()=>setSecretAnswer(a=>a.filter((_,j)=>j!==i))}>{w}</button>):<span>Tap pieces below</span>}</div><div className="cp-secret-pieces">{secretPieces.map((w,i)=>{const used=secretAnswer.filter(x=>x===w).length;const available=secretPieces.slice(0,i+1).filter(x=>x===w).length;return used<available?<button key={i} type="button" onClick={()=>setSecretAnswer(a=>[...a,w])}>{w}</button>:null})}</div><Button className="cp-neon-button cp-big-button" onClick={()=>void solveSecret()} disabled={busy||!secretAnswer.length}>SUBMIT SECRET</Button></>}{result?.result==="solved"&&<div className="cp-secret-win"><p>SECRET SOLVED!</p><span>Would you like to see today's secret?</span><div className="grid grid-cols-2 gap-3"><Button className="cp-neon-button" onClick={()=>void chooseSecret("yes")} disabled={busy}>YES</Button><Button variant="outline" className="cp-secondary-button" onClick={()=>void chooseSecret("no")} disabled={busy}>NO</Button></div></div>}{result?.result==="completed"&&<div className="cp-secret-win"><p>{secretChoice==="yes"?"SECRET REVEALED":"SECRET KEPT HIDDEN"}</p>{secretChoice==="yes"&&<div className="mt-3 rounded-xl border border-white/10 bg-black/20 p-3 text-left text-xs leading-relaxed">{result.secret}</div>}</div>}<Banner placement="seven_day_banner" className="cp-ad-banner"/></div>}

        {activity.slug==="playable_ad"&&<PlayableGate surface="seven_day_playable_only" onComplete={finish} onClose={onClose} required/>}
        {hasResult&&activity.slug!=="playable_ad"&&activity.slug!=="secret_reveal"&&activity.slug!=="lucky_card"&&<div className="cp-result-card"><div className="cp-result-icon"><Trophy className="size-7"/></div><p className="cp-result-kicker">RESULT REVEALED</p><p className="cp-result-title">{result?.reward_label||"Result revealed"}</p>{result?.reward_bc!==undefined&&<p className="cp-result-bc">{result.reward_bc>0?"+":""}{result.reward_bc} BC</p>}<p className="cp-result-detail">{result?.detail||result?.result}</p></div>}
        {adFor&&<div className="cp-ad-stage"><PlayableGate surface={"seven_day_"+adFor.slug+"_reveal"} onComplete={()=>{setAdFor(null);if(adFor.slug==="secret_reveal")void chooseSecret(secretChoice||"no");else finish();}} onClose={()=>setAdFor(null)} required/></div>}
        {completed&&<div className="cp-complete-card"><p>Today's activity is complete.</p><span>Continue into Psycho Panda and explore Circle Panda.</span><Button className="cp-neon-button mt-3" onClick={onClose}>CONTINUE</Button></div>}
      </>}
      <style>{`
.cp-game-shell{background:radial-gradient(circle at 50% -10%,rgba(52,211,153,.16),transparent 42%),#071713}
.cp-game-card{background:linear-gradient(180deg,rgba(18,35,31,.96),rgba(7,22,19,.98));box-shadow:0 16px 50px rgba(0,0,0,.32),inset 0 1px 0 rgba(255,255,255,.05)}
.cp-card-table,.cp-cup-stage{position:relative;min-height:285px;border-radius:24px;overflow:hidden;background:radial-gradient(circle at 50% 45%,rgba(45,255,183,.16),transparent 38%),linear-gradient(145deg,#0b2b24,#061613);border:1px solid rgba(90,255,198,.18);box-shadow:inset 0 0 45px rgba(45,255,183,.06)}
.cp-card-panda-hand{position:absolute;z-index:5;left:50%;top:22px;transform:translateX(-50%);font-size:42px;filter:drop-shadow(0 0 12px rgba(120,255,210,.65));animation:cpHandFloat 1.8s ease-in-out infinite}
.cp-card-fan{position:absolute;left:50%;bottom:28px;width:280px;height:190px;transform:translateX(-50%);perspective:900px}
.cp-real-card{position:absolute;left:50%;bottom:0;width:88px;height:140px;border-radius:14px;border:1px solid rgba(255,255,255,.28);transform-origin:50% 100%;transform-style:preserve-3d;transition:transform .45s cubic-bezier(.2,.8,.2,1),filter .35s;box-shadow:0 10px 30px rgba(0,0,0,.45),0 0 18px rgba(80,255,197,.16)}
.cp-real-card.card-0{transform:translateX(-118px) rotate(-13deg)}.cp-real-card.card-1{transform:translateX(-44px) rotate(-2deg)}.cp-real-card.card-2{transform:translateX(30px) rotate(10deg)}
.cp-real-card:hover{filter:brightness(1.18) drop-shadow(0 0 15px rgba(80,255,197,.45));transform:translateX(var(--x,0)) translateY(-10px) rotate(0)}
.cp-card-back,.cp-card-front{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;border-radius:14px;backface-visibility:hidden}.cp-card-back{background:linear-gradient(145deg,#153d33,#0a1f1b);font-size:34px;color:#9fffd7}.cp-card-back small,.cp-card-front small{font-size:8px;letter-spacing:2px}.cp-card-front{transform:rotateY(180deg);background:linear-gradient(145deg,#d9fff1,#73e8ba);color:#06251b;font-size:25px}.cp-real-card.is-flipping{animation:cpCardFlip .9s ease forwards}
.cp-card-table.is-mixing .cp-real-card.card-0{animation:cpMixA 1.45s ease-in-out}.cp-card-table.is-mixing .cp-real-card.card-1{animation:cpMixB 1.45s ease-in-out}.cp-card-table.is-mixing .cp-real-card.card-2{animation:cpMixC 1.45s ease-in-out}
.cp-card-table.is-mixing .cp-card-panda-hand{animation:cpHandMix 1.45s ease-in-out}
.cp-cups-row{position:absolute;left:50%;bottom:58px;display:flex;gap:12px;transform:translateX(-50%);z-index:4}.cp-cup-wrap{width:76px;height:105px;position:relative}.cp-cup{position:relative;width:70px;height:92px;transform-origin:50% 88%;filter:drop-shadow(0 12px 8px rgba(0,0,0,.55)) drop-shadow(0 0 14px rgba(85,255,197,.22))}.cp-cup-rim{position:absolute;left:5px;top:2px;width:60px;height:18px;border-radius:50%;background:linear-gradient(180deg,#effff9,#8ce8c5 45%,#277f65);border:1px solid rgba(255,255,255,.5);box-shadow:inset 0 3px 5px rgba(255,255,255,.55),0 0 10px rgba(98,255,207,.22)}.cp-cup-body{position:absolute;left:12px;top:11px;width:46px;height:72px;clip-path:polygon(8% 0,92% 0,78% 100%,22% 100%);border-radius:0 0 14px 14px;background:linear-gradient(90deg,#123e33,#6edcb6 44%,#164e3e);border:1px solid rgba(255,255,255,.25);box-shadow:inset -8px 0 10px rgba(0,0,0,.18),inset 7px 0 8px rgba(255,255,255,.12)}.cp-cup-shine{position:absolute;left:24px;top:19px;width:8px;height:43px;border-radius:99px;background:rgba(255,255,255,.34);filter:blur(1px)}.cp-cup-shadow{position:absolute;bottom:0;left:5px;width:66px;height:14px;border-radius:50%;background:#000;opacity:.4;filter:blur(5px)}.cp-cup-prize{position:absolute;z-index:2;left:50%;bottom:104px;transform:translateX(-50%);font-size:42px;filter:drop-shadow(0 0 18px rgba(255,236,130,.9));animation:cpPrizeBob .7s ease-in-out infinite alternate}.cp-panda-hand{position:absolute;z-index:6;font-size:42px;top:20px;filter:drop-shadow(0 0 12px rgba(255,255,255,.4))}.cp-hand-left{left:18px;transform:rotate(-10deg)}.cp-hand-right{right:18px;transform:rotate(10deg)}.cp-cup-stage.is-shuffling .cup-0{animation:cpCup0 1.15s ease-in-out infinite}.cp-cup-stage.is-shuffling .cup-1{animation:cpCup1 1.15s ease-in-out infinite}.cp-cup-stage.is-shuffling .cup-2{animation:cpCup2 1.15s ease-in-out infinite}.cp-cup-stage.is-shuffling .cp-panda-hand{animation:cpHandShuffle .65s ease-in-out infinite alternate}.cp-shuffle-label{position:absolute;left:50%;bottom:20px;transform:translateX(-50%);font-size:10px;font-weight:900;letter-spacing:1.6px;color:#b7ffe5;text-shadow:0 0 12px rgba(90,255,198,.6);white-space:nowrap}.cp-cup-reveal{margin-top:14px;border-radius:18px;padding:14px;text-align:center;background:linear-gradient(180deg,rgba(91,255,190,.15),rgba(255,255,255,.04));border:1px solid rgba(91,255,190,.3);box-shadow:0 0 28px rgba(91,255,190,.1);display:flex;flex-direction:column;gap:3px}.cp-cup-reveal span{font-size:25px}.cp-cup-reveal strong{font-size:15px}.cp-cup-reveal b{color:#9fffd7}
@keyframes cpHandFloat{50%{transform:translateX(-50%) translateY(8px) rotate(3deg)}}@keyframes cpHandMix{0%,100%{transform:translateX(-50%) rotate(-8deg)}50%{transform:translateX(-50%) translateY(42px) rotate(8deg)}}@keyframes cpCardFlip{0%{transform:translateX(-44px) rotateY(0) rotateZ(0)}50%{transform:translateX(-44px) rotateY(100deg) rotateZ(0) scale(1.08)}100%{transform:translateX(-44px) rotateY(180deg) rotateZ(0) scale(1.04)}}@keyframes cpMixA{0%,100%{transform:translateX(-118px) rotate(-13deg)}25%{transform:translateX(-10px) translateY(-24px) rotate(18deg)}55%{transform:translateX(62px) translateY(-6px) rotate(-8deg)}80%{transform:translateX(-76px) translateY(-14px) rotate(8deg)}}@keyframes cpMixB{0%,100%{transform:translateX(-44px) rotate(-2deg)}25%{transform:translateX(70px) translateY(-8px) rotate(16deg)}55%{transform:translateX(-108px) translateY(-20px) rotate(-15deg)}80%{transform:translateX(28px) translateY(-8px) rotate(5deg)}}@keyframes cpMixC{0%,100%{transform:translateX(30px) rotate(10deg)}25%{transform:translateX(-90px) translateY(-12px) rotate(-14deg)}55%{transform:translateX(-18px) translateY(-24px) rotate(10deg)}80%{transform:translateX(72px) translateY(-10px) rotate(-6deg)}}@keyframes cpCup0{0%,100%{transform:translateX(0) rotate(0)}35%{transform:translateX(90px) rotate(8deg)}70%{transform:translateX(-4px) rotate(-5deg)}}@keyframes cpCup1{0%,100%{transform:translateX(0) rotate(0)}35%{transform:translateX(-78px) rotate(-8deg)}70%{transform:translateX(84px) rotate(7deg)}}@keyframes cpCup2{0%,100%{transform:translateX(0) rotate(0)}35%{transform:translateX(-84px) rotate(-7deg)}70%{transform:translateX(8px) rotate(5deg)}}@keyframes cpHandShuffle{from{transform:translateY(-4px) rotate(-12deg)}to{transform:translateY(46px) rotate(12deg)}}@keyframes cpPrizeBob{to{transform:translateX(-50%) translateY(-8px) scale(1.08)}}
.cp-prize-choice{border-radius:18px;padding:16px 8px;display:flex;flex-direction:column;align-items:center;gap:8px;background:linear-gradient(145deg,rgba(50,100,85,.35),rgba(7,25,21,.9));border:1px solid rgba(111,255,207,.2);box-shadow:0 10px 25px rgba(0,0,0,.25);transition:.25s}.cp-prize-choice:hover{transform:translateY(-4px);border-color:rgba(111,255,207,.6);box-shadow:0 0 25px rgba(111,255,207,.16)}.cp-prize-choice span{font-size:34px}.cp-prize-choice small{font-size:9px;font-weight:900;letter-spacing:1px}
`}</style>
    </div>
  </DialogContent></Dialog>;
}
