/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrushRouteImport } from './routes/crush'
import { Route as DatingRouteImport } from './routes/dating'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HotSeatRouteImport } from './routes/hot-seat'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SweepstakesRouteImport } from './routes/sweepstakes'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrushRoute = CrushRouteImport.update({
  id: '/crush',
  path: '/crush',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingRoute = DatingRouteImport.update({
  id: '/dating',
  path: '/dating',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HotSeatRoute = HotSeatRouteImport.update({
  id: '/hot-seat',
  path: '/hot-seat',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SweepstakesRoute = SweepstakesRouteImport.update({
  id: '/sweepstakes',
  path: '/sweepstakes',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crush': typeof CrushRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/hot-seat': typeof HotSeatRoute
  '/leaders': typeof LeadersRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/sweepstakes': typeof SweepstakesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/crush': typeof CrushRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/hot-seat': typeof HotSeatRoute
  '/leaders': typeof LeadersRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/sweepstakes': typeof SweepstakesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups': typeof GroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crush': typeof CrushRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/hot-seat': typeof HotSeatRoute
  '/leaders': typeof LeadersRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/sweepstakes': typeof SweepstakesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crush'
    | '/dating'
    | '/events'
    | '/hot-seat'
    | '/leaders'
    | '/messages'
    | '/profile'
    | '/sweepstakes'
    | '/groups/$groupId'
    | '/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/crush'
    | '/dating'
    | '/events'
    | '/hot-seat'
    | '/leaders'
    | '/messages'
    | '/profile'
    | '/sweepstakes'
    | '/groups/$groupId'
    | '/groups'
  id:
    | '__root__'
    | '/'
    | '/crush'
    | '/dating'
    | '/events'
    | '/hot-seat'
    | '/leaders'
    | '/messages'
    | '/profile'
    | '/sweepstakes'
    | '/groups/$groupId'
    | '/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrushRoute: typeof CrushRoute
  DatingRoute: typeof DatingRoute
  EventsRoute: typeof EventsRoute
  HotSeatRoute: typeof HotSeatRoute
  LeadersRoute: typeof LeadersRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  SweepstakesRoute: typeof SweepstakesRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crush': {
      id: '/crush'
      path: '/crush'
      fullPath: '/crush'
      preLoaderRoute: typeof CrushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating': {
      id: '/dating'
      path: '/dating'
      fullPath: '/dating'
      preLoaderRoute: typeof DatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-seat': {
      id: '/hot-seat'
      path: '/hot-seat'
      fullPath: '/hot-seat'
      preLoaderRoute: typeof HotSeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweepstakes': {
      id: '/sweepstakes'
      path: '/sweepstakes'
      fullPath: '/sweepstakes'
      preLoaderRoute: typeof SweepstakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrushRoute: CrushRoute,
  DatingRoute: DatingRoute,
  EventsRoute: EventsRoute,
  HotSeatRoute: HotSeatRoute,
  LeadersRoute: LeadersRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  SweepstakesRoute: SweepstakesRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
