/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as CrushRouteImport } from './routes/crush'
import { Route as DatingRouteImport } from './routes/dating'
import { Route as EventsRouteImport } from './routes/events'
import { Route as HotSeatRouteImport } from './routes/hot-seat'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SweepstakesRouteImport } from './routes/sweepstakes'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'\nimport { Route as GamesCoinDropRouteImport } from './routes/games.coin-drop'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ConfessionsRouteImport } from './routes/confessions'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MusicTimeRouteImport } from './routes/music-time'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as StoreRouteImport } from './routes/store'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const CrushRoute = CrushRouteImport.update({
  id: '/crush',
  path: '/crush',
  getParentRoute: () => rootRouteImport,
} as any)
const DatingRoute = DatingRouteImport.update({
  id: '/dating',
  path: '/dating',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const HotSeatRoute = HotSeatRouteImport.update({
  id: '/hot-seat',
  path: '/hot-seat',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SweepstakesRoute = SweepstakesRouteImport.update({
  id: '/sweepstakes',
  path: '/sweepstakes',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesCoinDropRoute = GamesCoinDropRouteImport.update({\n  id: '/games/coin-drop',\n  path: '/games/coin-drop',\n  getParentRoute: () => rootRouteImport,\n} as any)\nconst AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfessionsRoute = ConfessionsRouteImport.update({
  id: '/confessions',
  path: '/confessions',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicTimeRoute = MusicTimeRouteImport.update({
  id: '/music-time',
  path: '/music-time',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRoute
  '/confessions': typeof ConfessionsRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/music-time': typeof MusicTimeRoute
  '/notifications': typeof NotificationsRoute
  '/store': typeof StoreRoute
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/crush': typeof CrushRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/hot-seat': typeof HotSeatRoute
  '/leaders': typeof LeadersRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/sweepstakes': typeof SweepstakesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/confessions': typeof ConfessionsRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/music-time': typeof MusicTimeRoute
  '/notifications': typeof NotificationsRoute
  '/store': typeof StoreRoute
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/crush': typeof CrushRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/hot-seat': typeof HotSeatRoute
  '/leaders': typeof LeadersRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/sweepstakes': typeof SweepstakesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/groups': typeof GroupsIndexRoute
}
export interface FileRoutesById {
  '/admin': typeof AdminRoute
  '/confessions': typeof ConfessionsRoute
  '/feed': typeof FeedRoute
  '/live': typeof LiveRoute
  '/music-time': typeof MusicTimeRoute
  '/notifications': typeof NotificationsRoute
  '/store': typeof StoreRoute
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/crush': typeof CrushRoute
  '/dating': typeof DatingRoute
  '/events': typeof EventsRoute
  '/hot-seat': typeof HotSeatRoute
  '/leaders': typeof LeadersRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/sweepstakes': typeof SweepstakesRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/groups/': typeof GroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/confessions'
    | '/feed'
    | '/live'
    | '/music-time'
    | '/notifications'
    | '/store'
    | '/'
    | '/activities'
    | '/crush'
    | '/dating'
    | '/events'
    | '/hot-seat'
    | '/leaders'
    | '/messages'
    | '/profile'
    | '/sweepstakes'
    | '/groups/$groupId'
    | '/groups/'
    | '/admin-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/confessions'
    | '/feed'
    | '/live'
    | '/music-time'
    | '/notifications'
    | '/store'
    | '/'
    | '/crush'
    | '/dating'
    | '/events'
    | '/hot-seat'
    | '/leaders'
    | '/messages'
    | '/profile'
    | '/sweepstakes'
    | '/groups/$groupId'
    | '/groups'
    | '/admin-dashboard'
  id:
    | '/admin'
    | '/confessions'
    | '/feed'
    | '/live'
    | '/music-time'
    | '/notifications'
    | '/store'
    | '__root__'
    | '/'
    | '/crush'
    | '/dating'
    | '/events'
    | '/hot-seat'
    | '/leaders'
    | '/messages'
    | '/profile'
    | '/sweepstakes'
    | '/groups/$groupId'
    | '/groups/'
    | '/admin-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRoute
  ConfessionsRoute: typeof ConfessionsRoute
  FeedRoute: typeof FeedRoute
  LiveRoute: typeof LiveRoute
  MusicTimeRoute: typeof MusicTimeRoute
  NotificationsRoute: typeof NotificationsRoute
  StoreRoute: typeof StoreRoute
  IndexRoute: typeof IndexRoute
  CrushRoute: typeof CrushRoute
  DatingRoute: typeof DatingRoute
  EventsRoute: typeof EventsRoute
  HotSeatRoute: typeof HotSeatRoute
  LeadersRoute: typeof LeadersRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  SweepstakesRoute: typeof SweepstakesRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confessions': {
      id: '/confessions'
      path: '/confessions'
      fullPath: '/confessions'
      preLoaderRoute: typeof ConfessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music-time': {
      id: '/music-time'
      path: '/music-time'
      fullPath: '/music-time'
      preLoaderRoute: typeof MusicTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crush': {
      id: '/crush'
      path: '/crush'
      fullPath: '/crush'
      preLoaderRoute: typeof CrushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dating': {
      id: '/dating'
      path: '/dating'
      fullPath: '/dating'
      preLoaderRoute: typeof DatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hot-seat': {
      id: '/hot-seat'
      path: '/hot-seat'
      fullPath: '/hot-seat'
      preLoaderRoute: typeof HotSeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sweepstakes': {
      id: '/sweepstakes'
      path: '/sweepstakes'
      fullPath: '/sweepstakes'
      preLoaderRoute: typeof SweepstakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRoute,
  ConfessionsRoute: ConfessionsRoute,
  FeedRoute: FeedRoute,
  LiveRoute: LiveRoute,
  MusicTimeRoute: MusicTimeRoute,
  NotificationsRoute: NotificationsRoute,
  StoreRoute: StoreRoute,
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  CrushRoute: CrushRoute,
  DatingRoute: DatingRoute,
  EventsRoute: EventsRoute,
  HotSeatRoute: HotSeatRoute,
  LeadersRoute: LeadersRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  SweepstakesRoute: SweepstakesRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
