revoke execute on function public.get_group_member_profiles_secure(uuid) from public, anon;
grant execute on function public.get_group_member_profiles_secure(uuid) to authenticated;
revoke execute on function public.report_group_user_secure(uuid,uuid,text,text) from public, anon;
grant execute on function public.report_group_user_secure(uuid,uuid,text,text) to authenticated;
revoke execute on function public.send_group_message_secure(uuid,text,uuid) from public, anon;
grant execute on function public.send_group_message_secure(uuid,text,uuid) to authenticated;
revoke execute on function public.send_group_media_secure(uuid,text,text,text,integer,boolean,text) from public, anon;
grant execute on function public.send_group_media_secure(uuid,text,text,text,integer,boolean,text) to authenticated;
revoke execute on function public.toggle_group_message_reaction(uuid,text) from public, anon;
grant execute on function public.toggle_group_message_reaction(uuid,text) to authenticated;
revoke execute on function public.leave_group_secure(uuid) from public, anon;
grant execute on function public.leave_group_secure(uuid) to authenticated;
revoke execute on function public.should_show_group_reward_ad(uuid) from public, anon;
grant execute on function public.should_show_group_reward_ad(uuid) to authenticated;
revoke execute on function public.mark_group_reward_ad_shown(uuid) from public, anon;
grant execute on function public.mark_group_reward_ad_shown(uuid) to authenticated;
revoke execute on function public.get_my_notifications(integer) from public, anon;
grant execute on function public.get_my_notifications(integer) to authenticated;
revoke execute on function public.check_admin_request() from public, anon;
grant execute on function public.check_admin_request() to authenticated;
revoke execute on function public.request_vip_group_video_match() from public, anon;
grant execute on function public.request_vip_group_video_match() to authenticated;