create or replace function public.admin_get_hot_seat_provider_settings() returns jsonb language plpgsql security definer set search_path=public,private,vault as $$
declare r public.hot_seat_provider_settings;
begin
 if not private.is_admin(auth.uid()) then raise exception 'Admin access required'; end if;
 select * into r from public.hot_seat_provider_settings where id=true;
 return jsonb_build_object('youtube_enabled',coalesce(r.youtube_enabled,true),'youtube_api_configured',nullif(r.youtube_api_key,'') is not null,'aws_enabled',coalesce(r.aws_enabled,false),'aws_region',coalesce(r.aws_region,''),'aws_channel_arn',coalesce(r.aws_channel_arn,''),'aws_playback_url',coalesce(r.aws_playback_url,''),'aws_access_key_configured',exists(select 1 from vault.secrets where name='circle_panda_hotseat_aws_secret'),'zegocloud_enabled',coalesce(r.zegocloud_enabled,false),'zegocloud_app_id',coalesce(r.zegocloud_app_id,''),'zegocloud_server_url',coalesce(r.zegocloud_server_url,''),'zegocloud_server_secret_configured',exists(select 1 from vault.secrets where name='circle_panda_hotseat_zegocloud_secret'),'push_enabled',coalesce(r.push_enabled,false),'push_project_id',coalesce(r.push_project_id,''),'push_client_email',coalesce(r.push_client_email,''),'push_credentials_configured',exists(select 1 from vault.secrets where name='circle_panda_hotseat_push_credentials'));
end $$;

create or replace function public.admin_save_hot_seat_provider_settings(p_youtube_enabled boolean default true,p_youtube_api_key text default null,p_aws_enabled boolean default false,p_aws_region text default '',p_aws_channel_arn text default '',p_aws_playback_url text default '',p_aws_access_key_id text default '',p_aws_secret_access_key text default null,p_zegocloud_enabled boolean default false,p_zegocloud_app_id text default '',p_zegocloud_server_url text default '',p_zegocloud_server_secret text default null,p_push_enabled boolean default false,p_push_project_id text default '',p_push_client_email text default '',p_push_credentials_json text default null)
returns jsonb language plpgsql security definer set search_path=public,private,vault as $$
declare sid uuid;
begin
 if not private.is_admin(auth.uid()) then raise exception 'Admin access required'; end if;
 insert into public.hot_seat_provider_settings(id,youtube_enabled,youtube_api_key,aws_enabled,aws_region,aws_channel_arn,aws_playback_url,aws_access_key_id,zegocloud_enabled,zegocloud_app_id,zegocloud_server_url,push_enabled,push_project_id,push_client_email,updated_at,updated_by)
 values(true,coalesce(p_youtube_enabled,true),coalesce(p_youtube_api_key,''),coalesce(p_aws_enabled,false),trim(coalesce(p_aws_region,'')),trim(coalesce(p_aws_channel_arn,'')),trim(coalesce(p_aws_playback_url,'')),trim(coalesce(p_aws_access_key_id,'')),coalesce(p_zegocloud_enabled,false),trim(coalesce(p_zegocloud_app_id,'')),trim(coalesce(p_zegocloud_server_url,'')),coalesce(p_push_enabled,false),trim(coalesce(p_push_project_id,'')),trim(coalesce(p_push_client_email,'')),now(),auth.uid())
 on conflict(id) do update set youtube_enabled=excluded.youtube_enabled,youtube_api_key=excluded.youtube_api_key,aws_enabled=excluded.aws_enabled,aws_region=excluded.aws_region,aws_channel_arn=excluded.aws_channel_arn,aws_playback_url=excluded.aws_playback_url,aws_access_key_id=excluded.aws_access_key_id,zegocloud_enabled=excluded.zegocloud_enabled,zegocloud_app_id=excluded.zegocloud_app_id,zegocloud_server_url=excluded.zegocloud_server_url,push_enabled=excluded.push_enabled,push_project_id=excluded.push_project_id,push_client_email=excluded.push_client_email,updated_at=now(),updated_by=auth.uid();
 if nullif(trim(coalesce(p_aws_secret_access_key,'')),'') is not null then select id into sid from vault.secrets where name='circle_panda_hotseat_aws_secret' limit 1; if sid is null then perform vault.create_secret(trim(p_aws_secret_access_key),'circle_panda_hotseat_aws_secret','Circle Panda Hot Seat AWS secret access key'); else perform vault.update_secret(sid,trim(p_aws_secret_access_key),'circle_panda_hotseat_aws_secret','Circle Panda Hot Seat AWS secret access key'); end if; end if;
 if nullif(trim(coalesce(p_zegocloud_server_secret,'')),'') is not null then select id into sid from vault.secrets where name='circle_panda_hotseat_zegocloud_secret' limit 1; if sid is null then perform vault.create_secret(trim(p_zegocloud_server_secret),'circle_panda_hotseat_zegocloud_secret','Circle Panda Hot Seat ZEGOCLOUD server secret'); else perform vault.update_secret(sid,trim(p_zegocloud_server_secret),'circle_panda_hotseat_zegocloud_secret','Circle Panda Hot Seat ZEGOCLOUD server secret'); end if; end if;
 if nullif(trim(coalesce(p_push_credentials_json,'')),'') is not null then select id into sid from vault.secrets where name='circle_panda_hotseat_push_credentials' limit 1; if sid is null then perform vault.create_secret(trim(p_push_credentials_json),'circle_panda_hotseat_push_credentials','Circle Panda Hot Seat push credentials'); else perform vault.update_secret(sid,trim(p_push_credentials_json),'circle_panda_hotseat_push_credentials','Circle Panda Hot Seat push credentials'); end if; end if;
 return public.admin_get_hot_seat_provider_settings();
end $$;

revoke all on function public.admin_get_hot_seat_provider_settings() from public,anon; grant execute on function public.admin_get_hot_seat_provider_settings() to authenticated;
revoke all on function public.admin_save_hot_seat_provider_settings(boolean,text,boolean,text,text,text,text,text,boolean,text,text,text,boolean,text,text,text) from public,anon;
grant execute on function public.admin_save_hot_seat_provider_settings(boolean,text,boolean,text,text,text,text,text,boolean,text,text,text,boolean,text,text,text) to authenticated;