-- Keep privileged MCM/WCW implementations in private; public RPCs are invoker wrappers.
create or replace function public.set_profile_gender_secure(p_gender text) returns text language sql security invoker set search_path=public,pg_temp as $$ select private.set_profile_gender_secure($1) $$;
create or replace function public.submit_crush_media_secure(p_media_url text,p_media_type text,p_caption text default '',p_emoji text default '🐼') returns uuid language sql security invoker set search_path=public,pg_temp as $$ select private.submit_crush_media_secure($1,$2,$3,$4) $$;
create or replace function public.react_to_crush_secure(p_nominee_id uuid,p_reaction text) returns boolean language sql security invoker set search_path=public,pg_temp as $$ select private.react_to_crush_secure($1,$2) $$;
create or replace function public.add_crush_comment_secure(p_nominee_id uuid,p_body text,p_attachment_url text default null,p_attachment_type text default null) returns uuid language sql security invoker set search_path=public,pg_temp as $$ select private.add_crush_comment_secure($1,$2,$3,$4) $$;
create or replace function public.report_crush_secure(p_nominee_id uuid,p_reason text,p_details text default null) returns uuid language sql security invoker set search_path=public,pg_temp as $$ select private.report_crush_secure($1,$2,$3) $$;
create or replace function public.delete_crush_submission(p_nominee_id uuid) returns jsonb language sql security invoker set search_path=public,pg_temp as $$ select private.delete_crush_submission($1) $$;
create or replace function public.start_crush_vote_ad_secure() returns jsonb language sql security invoker set search_path=public,pg_temp as $$ select private.start_crush_vote_ad_secure() $$;
create or replace function public.complete_crush_vote_ad_secure(p_session_id uuid) returns jsonb language sql security invoker set search_path=public,pg_temp as $$ select private.complete_crush_vote_ad_secure($1) $$;
create or replace function public.cast_crush_vote_secure(p_nominee_id uuid) returns jsonb language sql security invoker set search_path=public,pg_temp as $$ select private.cast_crush_vote_secure($1) $$;
create or replace function public.vote_crush(p_cycle_id uuid,p_nominee_id uuid) returns void language plpgsql security invoker set search_path=public,pg_temp as $$ begin if not exists(select 1 from public.crush_nominees where id=p_nominee_id and cycle_id=p_cycle_id) then raise exception 'NOMINEE_NOT_IN_CYCLE'; end if; perform public.cast_crush_vote_secure(p_nominee_id); end $$;
revoke all on function public.set_profile_gender_secure(text),public.submit_crush_media_secure(text,text,text,text),public.react_to_crush_secure(uuid,text),public.add_crush_comment_secure(uuid,text,text,text),public.report_crush_secure(uuid,text,text),public.delete_crush_submission(uuid),public.start_crush_vote_ad_secure(),public.complete_crush_vote_ad_secure(uuid),public.cast_crush_vote_secure(uuid),public.vote_crush(uuid,uuid) from public,anon;
grant execute on function public.set_profile_gender_secure(text),public.submit_crush_media_secure(text,text,text,text),public.react_to_crush_secure(uuid,text),public.add_crush_comment_secure(uuid,text,text,text),public.report_crush_secure(uuid,text,text),public.delete_crush_submission(uuid),public.start_crush_vote_ad_secure(),public.complete_crush_vote_ad_secure(uuid),public.cast_crush_vote_secure(uuid),public.vote_crush(uuid,uuid) to authenticated;