// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);

    // Surface every server-authoritative insufficient-BC response through one
    // global recovery dialog. The original response is returned unchanged so
    // each caller keeps its normal error handling.
    return fetch(input, { ...init, headers }).then(async (response) => {
      if (!response.ok && typeof window !== "undefined") {
        try {
          const clone = response.clone();
          const payload = await clone.json();
          const message = String(payload?.message ?? payload?.error_description ?? "");
          if (/insufficient\\s+(panda\\s+)?coins?|insufficient\\s+bc/i.test(message)) {
            const requiredMatch = message.match(/required\\s*[:=]\\s*(\\d+)/i);
            const balanceMatch = message.match(/(?:balance|available)\\s*[:=]\\s*(\\d+)/i);
            window.dispatchEvent(new CustomEvent("circle-panda-insufficient-bc", {
              detail: {
                required: requiredMatch ? Number(requiredMatch[1]) : undefined,
                balance: balanceMatch ? Number(balanceMatch[1]) : undefined,
                reason: message,
              },
            }));
          }
        } catch {
          // Preserve the original response even when an error body is not JSON.
        }
      }
      return response;
    });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  // Production fallback keeps the public Supabase client usable even when Vercel
  // has not yet received project environment variables. These are public client
  // values; privileged service-role secrets must never be placed here.
  const SUPABASE_URL =
    import.meta.env["VITE_SUPABASE_URL"] ||
    process.env["SUPABASE_URL"] ||
    "https://ddwtarfqzdhqdjsuzaft.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"] ||
    process.env["SUPABASE_PUBLISHABLE_KEY"] ||
    "sb_publishable_nTQolNRIM4F3SLU36uyhbg_bjLndmu9";

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    throw new Error(`[Supabase] Missing required environment variable(s): ${missing.join(", ")}.`);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: "pkce",
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
